height: 350
menubar: true
branding: false
file_picker_types: 'file image media'
file_picker_callback: true

automatic_uploads: true
image_title: true
toolbar:
  - undo redo | table | bullist numlist
plugins:
  - image
  - link
  - media
  - preview
  - lists
  - textcolor
  - colorpicker
  - advlist autolink lists link image charmap print preview anchor
  - searchreplace visualblocks fullscreen
  - insertdatetime media paste